

displayName: tc_churn_hpt_model1
studySpec:
  metrics:
  - metricId: val_accuracy
    goal: MINIMIZE
  parameters:
  - parameterId: lr
    doubleValueSpec:
      minValue: 0.0001
      maxValue: 0.1
    scaleType: UNIT_LOG_SCALE
  - parameterId: nbuckets
    integerValueSpec:
      minValue: 10
      maxValue: 25
    scaleType: UNIT_LINEAR_SCALE
  - parameterId: batch_size
    discreteValueSpec:
      values:
      - 15
      - 30
      - 50
    scaleType: UNIT_LINEAR_SCALE
  algorithm: ALGORITHM_UNSPECIFIED
trialJobSpec:
  baseOutputDirectory:
    outputUriPrefix: gs://iorek-byrnison/tc-cicd-dir/out/tc_churn_hpt_model1
  workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    pythonPackageSpec:
      args:
      - --train_data_path=gs://iorek-byrnison/tc-cicd-dir/data/tc-data/train.csv
      - --eval_data_path=gs://iorek-byrnison/tc-cicd-dir/data/tc-data/valid.csv
      - --batch_size=50
      - --num_examples_to_train_on=5000
      - --num_evals=100
      - --nbuckets=10
      - --lr=0.001
      - --nnsize=32 8
      executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-5:latest
      packageUris:
      - gs://iorek-byrnison/tc-cicd-dir/bin/tc_trainer-0.1.tar.gz
      pythonModule: trainer.hpt_task
    replicaCount: 1
